services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data: